dataset:
  name: tetrominoes
model:
  name: dti_sprites
  n_sprites: 19
  n_backgrounds: 0
  n_objects: 3
  freeze_sprite: 1
  inject_noise: 0.4
  encoder_name: resnet32
  transformation_sequence: identity
  transformation_sequence_bkg: color
  transformation_sequence_layer: color_position
  curriculum_learning: False
  curriculum_learning_bkg: False
  curriculum_learning_layer: False
  proto_init: constant
  mask_init: gaussian
  sprite_size: [24, 24]
  gaussian_weights_std: 5
  pred_occlusion: False
  estimate_minimum: True
  greedy_algo_iter: 1
training:
  batch_size: 32
  n_workers: 8
  optimizer:
    name: adam
    lr: 1.0e-4
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: [1, 0.1]
    milestones: [100, 200]
  n_epoches: 210
  train_stat_interval: 500
  val_stat_interval: 1000
  check_cluster_interval: 50
  eval_with_bkg: True
  eval_semantic: True
  seed: 65176
  visualizer_port:
  pretrained: 
  resume: 
